// <auto-generated />
using System;
using FlowSpline.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowSpline.Persistence.Migrations
{
    [DbContext(typeof(FlowSplineDbContext))]
    [Migration("20260509105408_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowSpline.Domain.AgentManagement.Aggregates.AgentDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("FlowSpline.Domain.AgentManagement.Aggregates.AgentTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SupervisorId")
                        .HasColumnType("uuid");

                    b.Property<string>("_memberIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("member_ids");

                    b.HasKey("Id");

                    b.ToTable("agent_teams", (string)null);
                });

            modelBuilder.Entity("FlowSpline.Domain.ExecutionEngine.Aggregates.ExecutionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("execution_runs", (string)null);
                });

            modelBuilder.Entity("FlowSpline.Domain.ToolRuntime.Aggregates.ToolDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tool_definitions", (string)null);
                });

            modelBuilder.Entity("FlowSpline.Domain.AgentManagement.Aggregates.AgentDefinition", b =>
                {
                    b.OwnsOne("FlowSpline.Domain.AgentManagement.ValueObjects.ModelSettings", "Model", b1 =>
                        {
                            b1.Property<Guid>("AgentDefinitionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxTokens")
                                .HasColumnType("integer")
                                .HasColumnName("max_tokens");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("model");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("provider");

                            b1.Property<double>("Temperature")
                                .HasColumnType("double precision")
                                .HasColumnName("temperature");

                            b1.HasKey("AgentDefinitionId");

                            b1.ToTable("agents");

                            b1.WithOwner()
                                .HasForeignKey("AgentDefinitionId");
                        });

                    b.OwnsMany("FlowSpline.Domain.AgentManagement.ValueObjects.Tool", "Tools", b1 =>
                        {
                            b1.Property<Guid>("AgentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("AgentId", "Name");

                            b1.ToTable("agent_tools", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AgentId");
                        });

                    b.Navigation("Model")
                        .IsRequired();

                    b.Navigation("Tools");
                });

            modelBuilder.Entity("FlowSpline.Domain.ExecutionEngine.Aggregates.ExecutionRun", b =>
                {
                    b.OwnsOne("FlowSpline.Domain.ExecutionEngine.ValueObjects.RunContext", "Context", b1 =>
                        {
                            b1.Property<Guid>("ExecutionRunId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("AgentId")
                                .HasColumnType("uuid")
                                .HasColumnName("agent_id");

                            b1.Property<string>("Input")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("input");

                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uuid")
                                .HasColumnName("session_id");

                            b1.HasKey("ExecutionRunId");

                            b1.HasIndex("AgentId", "SessionId");

                            b1.ToTable("execution_runs");

                            b1.WithOwner()
                                .HasForeignKey("ExecutionRunId");
                        });

                    b.Navigation("Context")
                        .IsRequired();
                });

            modelBuilder.Entity("FlowSpline.Domain.ToolRuntime.Aggregates.ToolDefinition", b =>
                {
                    b.OwnsOne("FlowSpline.Domain.ToolRuntime.ValueObjects.ToolSchema", "Schema", b1 =>
                        {
                            b1.Property<Guid>("ToolDefinitionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("InputSchema")
                                .HasColumnType("text")
                                .HasColumnName("input_schema");

                            b1.Property<string>("OutputSchema")
                                .HasColumnType("text")
                                .HasColumnName("output_schema");

                            b1.HasKey("ToolDefinitionId");

                            b1.ToTable("tool_definitions");

                            b1.WithOwner()
                                .HasForeignKey("ToolDefinitionId");
                        });

                    b.Navigation("Schema")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
