<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlowSpline.Application\FlowSpline.Application.csproj" />
    <ProjectReference Include="..\FlowSpline.Infrastructure\FlowSpline.Infrastructure.csproj" />
    <ProjectReference Include="..\FlowSpline.Persistence\FlowSpline.Persistence.csproj" />
  </ItemGroup>

</Project>
